language: python
python:
  - "3.7"
addons:
  apt:
    packages:
      - blender
sudo: false
install:
  - BLENDER_VERSION="2.80"
  - BLENDER_VERSION_SUFFIX=""
  - BLENDER_ARCHIVE="blender-${BLENDER_VERSION}${BLENDER_VERSION_SUFFIX}-linux-glibc217-x86_64"
  - mkdir tmp && cd tmp
  - wget  https://download.blender.org/release/Blender${BLENDER_VERSION}/${BLENDER_ARCHIVE}.tar.bz2
  - tar jxf ${BLENDER_ARCHIVE}.tar.bz2
  - mv ${BLENDER_ARCHIVE} blender
  - rm ${BLENDER_ARCHIVE}.tar.bz2
  - cd ..
  - ln -s ${PWD}/io_mesh_w3d ${PWD}/tmp/blender/${BLENDER_VERSION}/scripts/addons/io_mesh_w3d
script: python tests.py --blender ./tmp/blender/blender
