name: InstallationTests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install:
    runs-on: [ ubuntu-latest ]
  
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        BLENDER_VERSION: [ "2.81" ]

    env:
      BLENDER_ARCHIVE: "blender-${{ matrix.BLENDER_VERSION }}-linux-glibc217-x86_64"
    
    steps:
      - id: installBlender
        run: |
          mkdir tmp && cd tmp
          wget https://ftp.halifax.rwth-aachen.de/blender/release/Blender${{ matrix.BLENDER_VERSION }}/$BLENDER_ARCHIVE.tar.bz2
          tar jxf $BLENDER_ARCHIVE.tar.bz2
          mv $BLENDER_ARCHIVE blender
          rm $BLENDER_ARCHIVE.tar.bz2
          cd blender
          ./blender --background --python ../../ci_install.py
